name: tasty-stats
version: 0.2.0.2
description: Collect statistics of your Tasty testsuite in a CSV file
synopsis: Collect statistics of your Tasty testsuite in a CSV file
category: Testing
stability: experimental
author: Daniel Mendler <mail@daniel-mendler.de>
maintainer: Daniel Mendler <mail@daniel-mendler.de>
copyright: 2017 Daniel Mendler
license: MIT
github: minad/tasty-stats

extra-source-files:
- "*.md"

ghc-options:
- -Wall

tested-with:
  GHC == 7.10.3,
  GHC == 8.0.1

dependencies:
- base       >= 4.8    && < 5
- containers >= 0.4    && < 0.6
- directory  >= 1.1    && < 1.4
- process    >= 1.3    && < 1.5
- stm        >= 2.4    && < 2.6
- tagged     >= 0.7    && < 0.9
- tasty      >= 0.11.2 && < 0.12
- time       >= 1.5    && < 1.7

library:
  source-dirs: src
